### ISSUE TITLE
JCuda maven build fails due to Maven javadoc plugin

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda#27] opened 2019-10-15 11:20 UTC
With the recent javadoc plugin Jcuda maven build fails due to fake issue - missed javdoc files
Can be easily solved - using Xdoclint options:
                <configuration>
                <skip>true</skip>
                    <additionalparam>-Xdoclint:none</additionalparam>
                    <additionalJOptions>
                    <additionalOptions>-Xdoclint:none</additionalOptions>
                    <additionalJOption>-Xdoclint:-missing</additionalJOption>
                    </additionalJOptions>
                </configuration>
@jcuda , please update pom.xml and merge with release branch

**Comment by jcuda** [comment] 2019-10-15 15:16
Some (or most) of the JavaDocs are auto-generated (or manually generated) from the CUDA documentation, so there certainly *are* things like unresolved references, also issued as warnings during the javadoc creation my maven. 

(In fact, I once had some tool that basically read the (Doxygen-generated) documentation from the CUDA documentation, converted it to JavaDoc, and inserted it into the source code - crude, but saved a lot of time. Unfortunately, they changed the documentation style, and this is no longer reasonably possible. A general "Doxygen-To-Javadoc" conversion would be nice, and I have *some* infrastructure that could support this, but it's certainly on the bottom of my TODO list...))

However, the POM of the `jcuda-parent` project already contains the respective doclint option:
https://github.com/jcuda/jcuda-parent/blob/master/pom.xml#L176

(otherwise, the build would not work at all...)

Can you describe the conditions (i.e. your build command and the error) in more detail?

**Comment by PavelSosin-320** [comment] 2019-10-15 16:54
I simply build jcuda/jcuda branch no_critical using its own pom.xml. It contains Javadoc configuration <skip>true</true> to prevent doc generation for java-natives and subsequent maven failure but unfortunately it was enough for older plugin versions. It looks like every recent plugin version has own method how to prevent to doc generation: <skip>, **doclint parameter or option**. Build fails certainly at doclint phase :(. At least, build now succeeds.

**Comment by jcuda** [comment] 2019-10-15 17:01
I see. Two points:

- The "no_critical" branch was an initial experiment I'll probably reconstruct or possibly cherry-pick the most simple changes into the main branch, but am not sure when I can do that. 
- I probably did never try to build `jcuda` for itself. The usual procedure is to build everything, from `jcuda-main`. 

Regardless of the second point, `jcuda` should pick up the settings from `jcuda-parent`. If not, I'll have to figure out why (even though the simple solution of just adding the doclint setting in `jcuda` itself should do it, it *should* be handled by the parent project, usually...)

**Comment by jcuda** [comment] 2019-10-18 16:23
Assuming that

> At least, build now succeeds.

means that the issue is resolved, I'm closing this.

**Closed by jcuda** 2019-10-18 16:23 UTC
