### ISSUE TITLE
French locale issue with nvrtc

### ISSUE THREAD

**Issue by nicblanc** [jcuda/jcuda#4] opened 2016-04-21 14:12 UTC
While using JCuda on linux and compile cuda code with nvrtc and a french locale, every static floating values are "cut" after the dot.
`2.2e-10` become `2.0` and `3.14` become `3.0`.
Setting `LC_ALL=C` in the environnement bypass this issue.

**Comment by jcuda** [comment] 2016-04-21 16:47
Just as a backreference: https://github.com/jcuda/jcuda/pull/2#issuecomment-210087020 - and as already mentioned there: This is odd. It's not entirely clear where this "conversion" happens. But since the JCuda part does nor "parse" the input, and only forwards it, anonymously, as raw byte arrays, I'd suspect now that this is somehow caused inside the CUDA backend. 

As a quick test (to narrow down the search space) : The toolkit should contain some samples. Particularly, a sample 

    ...\NVIDIA Corporation\CUDA Samples\v7.5\0_Simple\vectorAdd_nvrtc

which does a vector addition with the NVRTC. If you modified the `vectorAdd_kernel.cu`, pragmatically, from 

    C[i] = A[i] + B[i];

to something like

    C[i] = A[i] + B[i] + 123.456;

And changed the input vectors in the `vectorAdd.cpp` to

    ...
    // Initialize the host input vectors
    for (int i = 0; i < numElements; ++i)
    {
        h_A[i] = (float)i
        h_B[i] = (float)i;
    }

and the verification to 

    ....
    // Verify that the result vector is correct
    for (int i = 0; i < numElements; ++i)
    {
        printf("At %d computed %f + %f = %f\n", i, h_A[i], h_B[i], h_C[i]);
        /* 
        if (fabs(h_A[i] + h_B[i] - h_C[i]) > 1e-5)
        {
            fprintf(stderr, "Result verification failed at element %d!\n", i);
            exit(EXIT_FAILURE);
        }
        */
    }

then it should either print something like

    At 0 computed 0.0 + 0.0 = 123
    At 1 computed 1.0 + 1.0 = 125
    ...

(showing that the parsing is messed up **in** the NVRTC compiler), or it should print

    At 0 computed 0.0 + 0.0 = 123.345
    At 1 computed 1.0 + 1.0 = 125.345
    ...

(which would cause some headaches for me ;-))

I agree that **if** it also happens in the native CUDA sample, then it should be reported to NVIDIA ASAP.

**Comment by nicblanc** [comment] 2016-04-22 13:00
Hi,
Sadly the sample's working ...

```
At 0 computed 0.000000 + 0.000000 = 123.456001
At 1 computed 1.000000 + 1.000000 = 125.456001
At 2 computed 2.000000 + 2.000000 = 127.456001
At 3 computed 3.000000 + 3.000000 = 129.455994
At 4 computed 4.000000 + 4.000000 = 131.455994
At 5 computed 5.000000 + 5.000000 = 133.455994
At 6 computed 6.000000 + 6.000000 = 135.455994
At 7 computed 7.000000 + 7.000000 = 137.455994
At 8 computed 8.000000 + 8.000000 = 139.455994
At 9 computed 9.000000 + 9.000000 = 141.455994
...
```

This is very tricky, I have no idea where the problem occurs.
As you said, the problem can't come from the JNI code, but I hadn't the problem when I was using `nvcc`.
I'm also running the same code with OpenCL and it's working perfectly.

Can this issue comes from the IDE ? Or maybe from the C compiler used to generate the libraries ?
Can this problem comes from encoding ? The sample's reading the cuda code from a file, I create it at runtime...

Here the locales currently defined on my computer:

```
nicblanc@nicblanc:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```

Maybe there is something wrong here too !

**Comment by jcuda** [comment] 2016-04-22 19:03
Ugh ... Now figuring out what's going wrong there may be fun. 

> Can this issue comes from the IDE ? Or maybe from the C compiler used to generate the libraries ?
Can this problem comes from encoding ? The sample's reading the cuda code from a file, I create it at runtime...

The C compiler that is used for the libraries never comes in touch with the acutal CUDA source code, and does not "parse" it in any way. 

When you say that you are **creating** it at runtime, I assume that this only refers to the `String` constants that you have in your program, and *not* to something like

    String mySourceCode = String.valueOf(123.456);

or even

    String mySourceCode = String.format("%f", 123.456);

because these may indeed do strange stuff. 

In any case, the example should work regardless of the locales and settings on your computer. Although the Java Strings (and JNI `jstrings`) do depend on the locale, the string "123.456" should remain as it is (there are no "Ümläüts" or other strange characters that may cause problems here). 

I just tried a pragmatic

    Locale.setDefault(Locale.FRANCE);

at the beginning of my `main` method, but it did not have any effect. So it would be great if you could help me with this. When you modify the program that I posted in https://github.com/jcuda/jcuda/pull/2#issuecomment-210085596 so that the core line of the kernel also is

        "        sum[i] = a[i] + b[i] + 123.456;" + "\n" +

and then print the PTX code by adding 

    ...
    nvrtcGetPTX(program, ptx);
    System.out.println(ptx[0]);  // <--- this line

then what does it print? Particularly, does the PTX contain a line like

    add.f64 	%fd2, %fd1, 0d405EDD2F1A9FBE77;

? The last constant is the important part here. This is basically the internal representation of "123.456". It should **not** be something like `0d405ec00000000000` (which would be 123.000). 

---

If this already prints the PTX with the wrong constant, then the error must be introduced earlier. Then, the next step would be to add a line like

    Logger::log(LOG_ERROR, "This is the converted source code:\n%s\n", nativeSrc);

**after** the line https://github.com/jcuda/jcuda/blob/b8d1a4aee3c338d1a48ae4228f18b115f210496a/JNvrtcJNI/src/JNvrtc.cpp#L148, recompile the library, run the sample and see what it prints there.

(Sorry, I know this is somewhat tedious, but right now, I don't see a more systematic way to locate the source of this problem. And the concerning thing here is that even **if** this prints the source code with the wrong number, I have no idea where this might come from or how it could be fixed - but let's first try to find the point where the locale actually is relevant). 

(Just to reassure: You had the same problem with the code in your orignal pull request, right?)

**Comment by jcuda** [comment] 2016-04-23 12:11
Maybe to elaborate what I meant above: When using something like

`myCode += String.format("%f", 123.456);` or `myCode += 123.456`  or `myCode += String.valueOf(123.456)`, then the actual `String` will be formatte according to the french locale by Java. So the String would be `123,345` (note the `,` instead of the `.`). And when *this* string is used in the Kernel, then the CUDA compiler may interpret this as the "comma operator" (which should then actually assign the value `456` to the variable, but ... it "would mess up things", in a broader sense...)

**Comment by nicblanc** [comment] 2016-05-09 13:06
Hi macro,

Sadly (in certain ways), I don't reproduce anymore.
I may have modify something that was the cause of the problem, but I don't know what.
Or maybe I just mixed up things between your version and my previous version of JNvrtc.

Anyway, you can close this issue, I let you know if this issue comes back.

One last thing, I notice that you use `(intptr_t)` in JNvrtc.cpp. 
On linux, it won't compile if you don't add `#include <stdint.h>` in `JNvrtc_common.hpp`

**Comment by nicblanc** [comment] 2016-05-09 14:08
Ok, it seems that I spoke a little bit too fast.

My code is the following, like it is printed by the line I've added in the JNvrtc.cpp:

```
extern "C"                                                           
__global__ void sum(                                                
   float* input,                                                       
   float* output,                                                      
   const int multiplier,                                               
   const unsigned int count)                                           
{                                                                      
   int i = blockIdx.x * blockDim.x + threadIdx.x;                      
   if(i < count)                                                       
       output[i] = input[i] + input[i] + 123.456f;             
}                                 
```              

I still reproduce, and the error is already present in the ptx: I have the line `	add.f32 	%f3, %f2, 0f42F60000;`                       

In single floating point precision, `0f42F60000` represents 123.0.
If I set `LC_ALL=C`, I have the following line; 	`add.f32 	%f3, %f2, 0f42F6E979;` which is what I should have.

I think that I do not reproduce with the Nvidia sample because the locale used in C is not the french one.

**Comment by jcuda** [comment] 2016-05-11 00:43
(Just a short note: I'll look into this in more detail ASAP, but am not sure when I'll be able to allocate the time for this)

**Comment by jcuda** [comment] 2016-05-11 17:10
That's all really strange. The source code input for the CUDA call is right, bug the PTX is wrong. I'd usually consider this as an issue of CUDA then, but as it does not happen in the plain C sample, there must be something else going wrong. 

(By the way: I'm also wondering about the `f32` - it should be an `f64` actually. But this might not be so important right now).

I have read a bit about locales in C and the `LC_ALL` setting, but still don't understand *what* is going wrong there - and *where*: It *must* be in the CUDA function, because the JNI part is passing the right string to it! 

Of course, I could now simply add a setting like you did in https://github.com/jcuda/jcuda/pull/2/commits/9fe76930d973f5631f562dad11e170eadf6d4190 , but am afraid that this may have unforseeable side-effects, and I don't see why this should be necessary just because of the JNI layer. I also searched the CUDA samples code for `"locale"` and `"LC_ALL"`, but they do not seem to appear anywhere. 

If anybody has an idea what might be wrong there, or how this could be resolved properly, I'd be glad to hear it.

**Comment by jcuda** [comment] 2016-05-12 09:15
This still bugs me, and I'm curious: Does the CUDA C sample show the same problem when you add

    std::setlocale(LC_ALL, "fr-FR");

at the beginning of the main method? If so, one explanation could be that the JVM sets the locale like that, depending on some internal system setting (some handwaving involved here, obviously...). In this case, adding 

    std::setlocale(LC_ALL, "C");

in the `JNI_OnLoad` could solve this, but again: I'm afraid that this might then affect *other* libraries that are loaded in the JVM, which may rely on the "right" (`fr-FR`) locale still being set...

**Comment by nicblanc** [comment] 2016-05-12 13:00
Hi Marco,

I have good news, I think I have found the problem.
I have done like you ask and add `std::setlocale(LC_ALL, "fr-FR");` at the beginning of the main method in the CUDA C sample.

This did not change a thing, the results were still "correct":
```
At 0 computed 0.000000 + 0.000000 = 123.456001
At 1 computed 1.000000 + 1.000000 = 125.456001
At 2 computed 2.000000 + 2.000000 = 127.456001
At 3 computed 3.000000 + 3.000000 = 129.455994
At 4 computed 4.000000 + 4.000000 = 131.455994
At 5 computed 5.000000 + 5.000000 = 133.455994
At 6 computed 6.000000 + 6.000000 = 135.455994
At 7 computed 7.000000 + 7.000000 = 137.455994
At 8 computed 8.000000 + 8.000000 = 139.455994
At 9 computed 9.000000 + 9.000000 = 141.455994
...
```

However, I have notice that the `LC_ALL` locale wasn't set on my computer:

```
nicblanc@nicblanc:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```

So instead of `std::setlocale(LC_ALL, "fr-FR");`, I tried `std::setlocale(LC_ALL, "");`.
Then I tested again and I reproduced my issue:
```
At 0 computed 0,000000 + 0,000000 = 123,000000
At 1 computed 1,000000 + 1,000000 = 125,000000
At 2 computed 2,000000 + 2,000000 = 127,000000
At 3 computed 3,000000 + 3,000000 = 129,000000
At 4 computed 4,000000 + 4,000000 = 131,000000
At 5 computed 5,000000 + 5,000000 = 133,000000
At 6 computed 6,000000 + 6,000000 = 135,000000
At 7 computed 7,000000 + 7,000000 = 137,000000
At 8 computed 8,000000 + 8,000000 = 139,000000
At 9 computed 9,000000 + 9,000000 = 141,000000
...
```

Notice that the problem occured also with `std::setlocale(LC_ALL, "fr_FR.UTF-8");`
I think that the problem has to come from Nvidia while using this specific locale.
I wonder if this is linux specific, I have to try on Windows on occasion to be sure.

We should start to think to contact Nvidia about it.

**Comment by jcuda** [comment] 2016-05-12 16:07
On the one hand, I agree that is *has* to be related to some internal workings of the CUDA library: The function receives the right string, but produces the wrong PTX, so there *is* something wrong. 

On the other hand (and from my experience so far), NVIDIA is not very ... (clears throat) ... "responsive" when it comes to error reports. In doubt, they could argue along the lines of "This is because to this JNI stuff that you're doing there - it's your fault!". (Or maybe "You're French! That's your fault!" ;-) ). 

(But seriously: Is it normal/correct that your `LC_ALL` is not set at all?)

---

In any case, I could not reproduce it here, neither in the original setup with the original sample, nor after adding any of

    std::setlocale(LC_ALL, "fr_FR.UTF-8");
    std::setlocale(LC_ALL, "fr_FR");
    std::setlocale(LC_ALL, "");
    std::setlocale(LC_ALL, "French_France.1252");
    std::locale::global(std::locale("French_France.1252"));

but of course, this doesn't mean too much, since it's a Windows system - and it's still not entirely clear to be what the effects of setting a locale is actually: There are odd details for "C locales" and "C++ locales", and obviously (even odder) differences on Windows and Linux, and I did not yet dig into all this.

So I agree: This could be asked for in the NVIDIA CUDA forums, with a description of the problem (and a reference to the sample and the `setlocale` call that causes it to bail out) - maybe someone has an idea...

**Comment by jcuda** [comment] 2016-09-15 15:36
This is still open. @nicblanc  Did you gain any new insights here? If not, depending on your answer, I could either close this issue, or try to post a thread at the NVIDIA forums ... although the latter would be a bit stange, because I still could not reproduce the issue.

**Comment by jcuda** [comment] 2017-02-27 21:19
No feedback from france. Closing.

**Closed by jcuda** 2017-02-27 21:19 UTC
