### ISSUE TITLE
Maven install libraries issue - pom file is never  instaled

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda#29] opened 2019-10-18 11:51 UTC
Either maven-install plagin is not running or generate pom file parameter is missed. Indeed, when I run maven install on local maven progects: jcuda,jcublas, etc. only jar files are installed in local maven repository, pom is always missed. It looks like generate pom parameter should be added explicetely.
mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file  -Dfile=path-to-your-artifact-jar \
                                                                              -DgroupId=your.groupId \
                                                                              -DartifactId=your-artifactId \
                                                                              -Dversion=version \
                                                                              -Dpackaging=jar \
                                                                              -DgeneratePom=true

**Comment by jcuda** [comment] 2019-10-18 16:19
When I do an

    cd jcuda-parent
    mvn install
    cd..
    cd jcuda-main
    mvn install

without having `org/jcuda` in my local maven repo, then it installs all JCuda libraries in the local maven repo, and each of them contains the respective POM file.

Closing with "cannot reproduce". Feel free to describe this with more details.

**Closed by jcuda** 2019-10-18 16:19 UTC

**Comment by PavelSosin-320** [comment] 2019-10-22 10:03
What I'm trying to do:
1. Maven build of jcuda giving version 10.1.0 because I took specific brach no_critical as pre-release
2.Maven build jcublas referencing jcuda giving version SNAPSHOT as it assuming when build takes sources from master branch with my own uncommited changes in the tests only for testing purposes.
3. Create my own project refrencing pre-release jcuda 10.1.0 and jcublas SNAPSHOT. Of course I don't want to commit something because my project is not yet tested and I have no automatic testing pipeline and my future changes will be submitted to master and build version will be SNAPSHOT. I hope all changes will be submitted after code review and merged into pre-release or release version to make them available for other developers who desire to use SNAPSHOT versions and run integration tests with their own features under develompent.
If somebody wants to start development of new jcuda extension like jcublas it can be done based on jcuda SNAPSHOT, i.e. master branch or pre/release.
maven install plugin is mandatory to make artifact consistently available in the local repository and it indeed works for me. Maven doesn't need any manual pre-installation steps.

**Comment by jcuda** [comment] 2019-10-22 12:58
Not sure if I understood this correctly, but the main point of this issue seems to be that the version number in the POM is

    <version>10.1.0</version>

but you want it to be

    <version>10.1.1-SNAPTHOT</version>

Is that correct?

If this is correct, then you're right: Usually, the POM in the SCM should basically *always* be a `SNAPSHOT` version. A `maven release` call then does all the work:

- the version is changed to the "final" version (omitting the `SNAPSHOT`)
- the change is committed and pushed
- the artifacts are built
- the artifacts are deployed to staging for central
- the version number is updated to `...next-SNAPSHOT`
- the change is committed and pushed

However, in the case of JCuda, the maven release plugin cannot be sensibly used, due to the native libraries that are coming from several contributors and have to be packed and uploaded manually. 

The workaround for now is to add the `SNAPSHOT` suffix (in doubt, in an own branch). If you have **specific** hints about how to solve this issue, I'd be interested to hear them.

**Comment by PavelSosin-320** [comment] 2019-10-23 08:09
Hi Marco,
It looks like Java 9 provides out-off-thebox solution for such use-case in
the form of Java modules, i.e. separate Maven artifacts with - native
extensilbility mechanism. Every extension module is independend plugin with
its own binaries, DLLs SOs and can be developed separately and insalled
separately from Maven repository (no download site, stable, certified  url
!!!) . I never tried it because Web and Cloud applications which are my
real professional area last 7 years use even more sofisticated mechanisms
allowing independend delivery extensions via marketplace.
Provider design pattern is all about simple configuration of Java class
instance to be created using confiuration in the property file.
All CUDA libraries are exactly the same from Java object lifecycle point of
view: from initialize to destroy.

**Comment by PavelSosin-320** [comment] 2019-10-23 09:41
P.S. I suppose that maven dependency plugin allows to install DLLs packed
into jar during project building without overloading Class static
initialization with extra 4 IO count and coding

**Comment by jcuda** [comment] 2019-10-23 16:49
So you think you can propose a solution, via a pull request?

**Comment by PavelSosin-320** [comment] 2019-10-23 21:11
Give me please few days more to see how to build Java module with DLL in
bin file and how to extract it directly into java_library_path
There is  some distance between "I know how to do it" and "I tested and it
works OK with tests green"

**Comment by jcuda** [comment] 2019-10-24 18:47
Sure. Admittedly, I haven't looked as deeply into the "Java Module System" as I should (I'm still mainly on Java 8, with some Java 13 experiments in the context of Project Panama), but think that parts of it *might* make things simpler when it comes to native binaries. Right now, the fact that the natives have to be unpacked to the "temp"-directory and loaded from there is cumbersome (although the [`LibUtils`](https://github.com/jcuda/jcuda/blob/master/JCudaJava/src/main/java/jcuda/LibUtils.java) now handle this reasonably well). 

*If* there is a nice solution, I might still hesitate to integrate it: Right now, from a technical point of view, JCuda works with Java 7 (or even lower, if necessary). Raising the dependency to Java 9 could cause some compatibility issues. But it certainly could show one path that could be taken medium term.

**Comment by PavelSosin-320** [comment] 2019-10-28 15:14
Meanwhile, I succeeded to create Module template based on JCublas project
which contains both java code and Windows DLL as "Non-java Maven
dependency" and published it imy local repository as JCublasModule artifact
and additional dependencies artifacts packed as jars. The problem is in
maven Dependency plugin which according documentation, should be able to
unpack Module's additional artifact into folder by my choice, namely ${
JCudaLibraryPath} at the source processing phase, i.e. should work as
installer. Unfortunately, the maven dependency plugin doesn't interpret
correctly "ArtifactItem" definition in my pom although doesn't recognize
any issue when execute my pom in verification mode. Search in Stack
overflow shows that this plugin is very capricious lady.

**Comment by jcuda** [comment] 2019-10-28 16:15
Not really any specific plugin. Maven+Natives=Headaches, to say the least. There are approaches like https://www.mojohaus.org/maven-native/native-maven-plugin/compile-mojo.html or https://github.com/cmake-maven-project/cmake-maven-project (and I think that I played with some approaches here, mainly for JOCL, a while ago). But one problem will persist: At one point, one needs *all* native libraries on *one* system, and they can (hardly) be all *built* on the same system. 

(BTW: Things like the directory structure of JCuda, with the `JCudaRuntimeJNI` etc. directories, are basically "legacy". They *could* be changed to the more maven-compliant `src/main/native` structure (like it is done in JOCL), but that would rather be a cosmetic change and not make anything easier here...)
